# Generated by Django 3.2.4 on 2021-07-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='text',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
